# Generated by Django 2.0.5 on 2018-11-26 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NomaFunc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epr', models.CharField(max_length=100, unique=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'noma_func',
            },
        ),
        migrations.CreateModel(
            name='NomaGrp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Group Name')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('sdir', models.FilePathField(allow_files=False, allow_folders=True, max_length=200, path='d:/xna/sourcedata', recursive=True, verbose_name='Source File Folder')),
                ('ldir', models.FilePathField(allow_files=False, allow_folders=True, max_length=200, path='d:/xna/logs/', recursive=True, verbose_name='Log File Folder')),
            ],
            options={
                'verbose_name': 'Noma Group',
                'db_table': 'noma_grp',
            },
        ),
        migrations.CreateModel(
            name='NomaGrpSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfile', models.CharField(max_length=100)),
                ('ttbl', models.CharField(max_length=30)),
                ('ocsv', models.BooleanField(default=True)),
                ('grp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='noma.NomaGrp')),
            ],
            options={
                'verbose_name': 'Noma Set',
                'verbose_name_plural': 'Noma Sets',
                'db_table': 'noma_grpset',
            },
        ),
        migrations.CreateModel(
            name='NomaSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('type', models.CharField(max_length=3)),
                ('sepr', models.CharField(blank=True, max_length=100, null=True)),
                ('eepr', models.CharField(blank=True, max_length=100, null=True)),
                ('depr', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'noma_set',
            },
        ),
        migrations.CreateModel(
            name='NomaSetAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.DecimalField(decimal_places=2, max_digits=3)),
                ('nepr', models.CharField(blank=True, max_length=100, null=True)),
                ('spos', models.SmallIntegerField(blank=True, null=True)),
                ('epos', models.SmallIntegerField(blank=True, null=True)),
                ('sepr', models.CharField(blank=True, max_length=100, null=True)),
                ('eepr', models.CharField(blank=True, max_length=100, null=True)),
                ('fepr', models.CharField(blank=True, max_length=100, null=True)),
                ('fname', models.CharField(blank=True, max_length=50, null=True)),
                ('skipseq', models.SmallIntegerField(blank=True, null=True)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='noma.NomaSet')),
                ('tfunc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='noma.NomaFunc')),
            ],
            options={
                'db_table': 'noma_setact',
            },
        ),
        migrations.AddField(
            model_name='nomagrpset',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grps', to='noma.NomaSet'),
        ),
        migrations.AlterUniqueTogether(
            name='nomasetact',
            unique_together={('set', 'seq')},
        ),
        migrations.AlterUniqueTogether(
            name='nomagrpset',
            unique_together={('grp', 'set')},
        ),
    ]
