# Generated by Django 2.0.5 on 2018-11-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomaset',
            name='type',
            field=models.CharField(choices=[('tx', 'Text/XML'), ('js', 'JSON'), ('bi', 'Binary')], default='tx', max_length=2),
        ),
    ]
