# Generated by Django 2.0.5 on 2018-11-27 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noma', '0003_auto_20181126_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='queGrp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Group Name')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('ldir', models.FilePathField(allow_files=False, allow_folders=True, max_length=200, path='d:/xna/logs/', recursive=True, verbose_name='Log File Folder')),
                ('tfile', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Query Group',
                'db_table': 'que_grp',
            },
        ),
        migrations.CreateModel(
            name='queGrpSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='noma.queGrp')),
            ],
            options={
                'verbose_name': 'Query Set',
                'verbose_name_plural': 'Query Sets',
                'db_table': 'que_grpset',
            },
        ),
        migrations.CreateModel(
            name='queSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
            ],
            options={
                'db_table': 'que_set',
            },
        ),
        migrations.CreateModel(
            name='queSetSql',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.DecimalField(decimal_places=0, max_digits=3)),
                ('sqlq', models.CharField(blank=True, max_length=300, null=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sqls', to='noma.queSet')),
            ],
            options={
                'db_table': 'que_setsql',
                'ordering': ['seq'],
            },
        ),
        migrations.AlterModelOptions(
            name='nomasetact',
            options={'ordering': ['seq']},
        ),
        migrations.AddField(
            model_name='quegrpset',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grps', to='noma.queSet'),
        ),
        migrations.AlterUniqueTogether(
            name='quesetsql',
            unique_together={('set', 'seq')},
        ),
        migrations.AlterUniqueTogether(
            name='quegrpset',
            unique_together={('grp', 'set')},
        ),
    ]
