# Generated by Django 2.0.5 on 2018-11-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noma', '0004_auto_20181127_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesetsql',
            name='name',
            field=models.CharField(default='dummy', max_length=50),
            preserve_default=False,
        ),
    ]
