# Generated by Django 2.0.5 on 2018-11-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noma', '0005_quesetsql_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queset',
            options={'verbose_name': 'Query Set'},
        ),
        migrations.AlterField(
            model_name='nomasetact',
            name='seq',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
