# Generated by Django 2.0.5 on 2018-11-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noma', '0006_auto_20181128_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomasetact',
            name='seq',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
