# Generated by Django 2.0.5 on 2018-11-30 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noma', '0007_auto_20181128_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomasetact',
            old_name='skipseq',
            new_name='skip',
        ),
    ]
