# Generated by Django 2.0.5 on 2018-11-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noma', '0008_auto_20181130_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomasetact',
            old_name='skip',
            new_name='skipb',
        ),
        migrations.AddField(
            model_name='nomasetact',
            name='skipf',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
