# Generated by Django 2.0.5 on 2018-11-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noma', '0009_auto_20181201_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomasetact',
            name='skipb',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nomasetact',
            name='skipf',
            field=models.SmallIntegerField(default=0),
        ),
    ]
