# Generated by Django 2.0.5 on 2018-12-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noma', '0010_auto_20181201_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomasetact',
            name='varr',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
