# Generated by Django 2.0.5 on 2018-12-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noma', '0011_nomasetact_varr'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomasetact',
            name='tpar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nomafunc',
            name='epr',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='nomasetact',
            name='fname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
