# Generated by Django 2.0.5 on 2018-12-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noma', '0012_auto_20181211_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomasetact',
            name='fname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
