# Generated by Django 2.0.5 on 2018-12-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noma', '0013_auto_20181211_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomasetact',
            name='tpar',
        ),
    ]
