# Generated by Django 2.0.5 on 2018-12-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noma', '0015_nomasetact_fchar'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomaStrMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ostr', models.CharField(max_length=50, unique=True)),
                ('cstr', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'noma_strmap',
            },
        ),
    ]
