# Generated by Django 2.0.5 on 2018-12-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noma', '0016_nomastrmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomastrmap',
            name='cstr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
