# Generated by Django 2.0.5 on 2018-12-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noma', '0017_auto_20181215_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomafunc',
            name='epr',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
