# Generated by Django 2.0.5 on 2018-12-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noma', '0018_auto_20181221_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomastrmap',
            name='ctag',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='nomastrmap',
            name='ostr',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='nomastrmap',
            unique_together={('ctag', 'ostr')},
        ),
    ]
