# Generated by Django 2.0.5 on 2019-01-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noma', '0019_auto_20181226_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomafunc',
            options={'verbose_name_plural': 'Transform Fucntions'},
        ),
        migrations.AlterModelOptions(
            name='nomaset',
            options={'verbose_name_plural': 'Noma Sets'},
        ),
        migrations.AlterModelOptions(
            name='nomastrmap',
            options={'verbose_name_plural': 'Strings Maps'},
        ),
        migrations.AddField(
            model_name='nomagrp',
            name='gtag',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='nomaset',
            name='type',
            field=models.CharField(choices=[('tx', 'Text/XML'), ('js', 'JSON'), ('bi', 'Binary'), ('p2', 'PCAP2pass')], default='tx', max_length=2),
        ),
    ]
