# Generated by Django 2.0.5 on 2019-01-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noma', '0020_auto_20190102_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomaQFunc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epr', models.CharField(max_length=50, unique=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Q-Fucntions',
                'db_table': 'noma_qfunc',
            },
        ),
        migrations.AlterModelOptions(
            name='nomafunc',
            options={'verbose_name_plural': 'T-Fucntions'},
        ),
    ]
