# Generated by Django 2.0.5 on 2019-01-03 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noma', '0021_auto_20190103_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomagrp',
            options={'verbose_name': ' Noma Group'},
        ),
        migrations.AlterModelOptions(
            name='nomagrpset',
            options={'verbose_name': 'Noma Set', 'verbose_name_plural': ' Noma Sets'},
        ),
        migrations.AlterModelOptions(
            name='nomaset',
            options={'verbose_name_plural': ' Noma Sets'},
        ),
        migrations.AlterModelOptions(
            name='quegrp',
            options={'verbose_name': ' Query Group'},
        ),
        migrations.AlterModelOptions(
            name='queset',
            options={'verbose_name': ' Query Set'},
        ),
        migrations.RenameField(
            model_name='quesetsql',
            old_name='desc',
            new_name='qpar',
        ),
        migrations.RemoveField(
            model_name='quesetsql',
            name='sqlq',
        ),
        migrations.AddField(
            model_name='quesetsql',
            name='qfunc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='noma.NomaQFunc'),
        ),
        migrations.AddField(
            model_name='quesetsql',
            name='stbl',
            field=models.CharField(default='dumm', max_length=30),
            preserve_default=False,
        ),
    ]
