# Generated by Django 2.0.5 on 2019-01-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noma', '0022_auto_20190103_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomafunc',
            options={'verbose_name_plural': 'T-Functions'},
        ),
        migrations.AlterModelOptions(
            name='nomaqfunc',
            options={'verbose_name_plural': 'Q-Functions'},
        ),
        migrations.AddField(
            model_name='quegrp',
            name='gpar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quegrpset',
            name='spar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quegrp',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quegrp',
            name='ldir',
            field=models.FilePathField(allow_files=False, allow_folders=True, max_length=200, path='d:/xna/logs/', recursive=True, verbose_name='Output Folder'),
        ),
    ]
