# Generated by Django 2.0.5 on 2019-01-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noma', '0023_auto_20190103_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomaqfunc',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='quegrp',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='quegrp',
            name='gpar',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='quegrpset',
            name='spar',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='queset',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='quesetsql',
            name='qpar',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
