# Generated by Django 2.0.5 on 2019-01-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noma', '0024_auto_20190103_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomafunc',
            options={'verbose_name_plural': '[E] T-Functions'},
        ),
        migrations.AlterModelOptions(
            name='nomagrp',
            options={'verbose_name_plural': '  [O] Noma Groups (Import Data)'},
        ),
        migrations.AlterModelOptions(
            name='nomaqfunc',
            options={'verbose_name_plural': '[E] Q-Functions'},
        ),
        migrations.AlterModelOptions(
            name='nomaset',
            options={'verbose_name_plural': ' [A] Noma Sets'},
        ),
        migrations.AlterModelOptions(
            name='nomastrmap',
            options={'verbose_name_plural': ' [A] Strings Maps'},
        ),
        migrations.AlterModelOptions(
            name='quegrp',
            options={'verbose_name_plural': '  [O] Query Groups (Export Data)'},
        ),
        migrations.AlterModelOptions(
            name='queset',
            options={'verbose_name_plural': ' [A] Query Sets'},
        ),
        migrations.AlterField(
            model_name='nomagrp',
            name='gtag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='nomagrp',
            name='ldir',
            field=models.FilePathField(allow_files=False, allow_folders=True, max_length=200, path='d:/xna/logs', recursive=True, verbose_name='Output File Folder'),
        ),
        migrations.AlterField(
            model_name='quegrp',
            name='ldir',
            field=models.FilePathField(allow_files=False, allow_folders=True, max_length=200, path='d:/xna/logs', recursive=True, verbose_name='Output Folder'),
        ),
    ]
