# Generated by Django 2.0.5 on 2019-01-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noma', '0025_auto_20190110_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomagrp',
            options={'verbose_name_plural': '  [O] Import Groups'},
        ),
        migrations.AlterModelOptions(
            name='quegrp',
            options={'verbose_name_plural': '  [O] Query Groups'},
        ),
        migrations.AddField(
            model_name='nomafunc',
            name='pars',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nomaqfunc',
            name='pars',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
