# Generated by Django 2.0.5 on 2019-01-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noma', '0026_auto_20190113_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesetsql',
            name='qpar',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
